### ISSUE TITLE
Graal Groovy Native Image Support - nativeCompile / nativeRun

### ISSUE THREAD

**Issue by codeconsole** [micronaut-projects/micronaut-groovy#323]
### Feature description

Are there any plans for getting Micronaut Groovy apps running natively?

I don't see any guidance on what the current state is or if there was or ever will be plans to support it.

https://guides.micronaut.io/latest/micronaut-creating-first-graal-app.html

However, perhaps the nativeCompile / nativeRun tasks should be removed as available tasks from Groovy apps if there are no plans to support it because it is confusing to new users.

# App Creation
```
sdk use micronaut 3.3.4
sdk use java 22.0.0.2.r11-grl 
mn create-app --lang groovy hello 
cd hello
./gradlew nativeCompile
```

# Output
```
========================================================================================================================
GraalVM Native Image: Generating 'hello'...
========================================================================================================================
[1/7] Initializing...                                                                                    (4.8s @ 0.23GB)
 Version info: 'GraalVM 22.0.0.2 Java 11 CE'
 3 user-provided feature(s)
  - com.oracle.svm.polyglot.groovy.GroovyIndyInterfaceFeature
  - io.micronaut.buffer.netty.NettyFeature
  - io.micronaut.http.netty.graal.HttpNettyFeature
[2/7] Performing analysis...  [**************]                                                          (58.0s @ 5.08GB)
  14,861 (91.44%) of 16,252 classes reachable
  22,078 (64.90%) of 34,021 fields reachable
  77,319 (61.59%) of 125,547 methods reachable
     683 classes,   647 fields, and 1,831 methods registered for reflection
      68 classes,    89 fields, and    55 methods registered for JNI access

Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.invoke.MethodHandleNatives.setCallSiteTargetNormal(CallSite, MethodHandle) is reachable
------------------------------------------------------------------------------------------------------------------------To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.

Detailed message:
Trace: 
        at parsing java.lang.invoke.CallSite.setTargetNormal(CallSite.java:286)
Call path from entry point to java.lang.invoke.CallSite.setTargetNormal(MethodHandle): 
        at java.lang.invoke.CallSite.setTargetNormal(CallSite.java:286)
        at java.lang.invoke.MutableCallSite.setTarget(MutableCallSite.java:156)
        at java.lang.invoke.SwitchPoint.invalidateAll(SwitchPoint.java:225)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface.invalidateSwitchPoints(IndyInterface.java:186)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface.lambda$static$0(IndyInterface.java:172)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.fireConstantMetaClassUpdate(MetaClassRegistryImpl.java:393)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.setMetaClass(MetaClassRegistryImpl.java:282)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.removeMetaClass(MetaClassRegistryImpl.java:287)
        at org.codehaus.groovy.runtime.InvokerHelper.removeClass(InvokerHelper.java:94)
        at groovy.lang.GroovyClassLoader.clearCache(GroovyClassLoader.java:1175)
        at groovy.lang.GroovyClassLoader.close(GroovyClassLoader.java:1193)
        at com.oracle.svm.core.posix.NativeSecureRandomFilesCloserShutdownHook.close(PosixSunSecuritySubstitutions.java:86)
        at com.oracle.svm.core.posix.NativeSecureRandomFilesCloserShutdownHook.run(PosixSunSecuritySubstitutions.java:70)
        at java.lang.Shutdown.runHooks(Shutdown.java:130)
        at java.lang.Shutdown.shutdown(Shutdown.java:186)
        at com.oracle.svm.core.jdk.RuntimeSupport.shutdown(RuntimeSupport.java:151)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
                        9.7s (15.2% of total time) in 27 GCs | Peak RSS: 6.72GB | CPU load: 9.29
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /Users/sheiberg/Documents/workspace/hello/build/native/nativeCompile/hello.build_artifacts.txt
========================================================================================================================
Failed generating 'hello' after 1m 3s.
Error: Image build request failed with exit status 1

> Task :nativeCompile FAILED

FAILURE: Build failed with an exception.


* What went wrong:
Execution failed for task ':nativeCompile'.
> Process 'command '/Users/sheiberg/.sdkman/candidates/java/22.0.0.2.r11-grl/bin/native-image'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 7s
5 actionable tasks: 5 executed
```

# System Info
```
% sw_vers                           
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
% sysctl -a | grep brand           
machdep.cpu.brand: 0
machdep.cpu.brand_string: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
```

**Comment by codeconsole** [comment]
https://github.com/croz-ltd/klokwrk-project/blob/master/support/documentation/article/groovy-graalvm-native-image/groovy-graalvm-native-image.md

**Comment by linghengqian** [comment]
- Is it convenient for you to open a new issue in the groovy area of ​​apache jira?  This seems to be a common phenomenon and has nothing to do with previous fixes in Groovy 4.

**Comment by codeconsole** [comment]
@linghengqian not following you.  Previous fixes? Are you saying Groovy 4 works? 

I am not configuring anything. I am just using the latest micronaut cli.  You would expect if you create an app with the cli, it would build.

```
sdk use micronaut 3.7.1
sdk use java 22.2.r11-grl
mn create-app --lang groovy hello 
./gradlew nativeCompile
```

```
GraalVM Native Image: Generating 'hello' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                   (17.8s @ 0.18GB)
 Version info: 'GraalVM 22.2.0 Java 11 CE'
 Java version info: '11.0.16+8-jvmci-22.2-b06'
 C compiler: cc (apple, arm64, 14.0.0)
 Garbage collector: Serial GC
 5 user-specific feature(s)
 - com.oracle.svm.polyglot.groovy.GroovyIndyInterfaceFeature
 - io.micronaut.buffer.netty.NettyFeature
 - io.micronaut.core.graal.ServiceLoaderFeature
 - io.micronaut.http.netty.graal.HttpNettyFeature
 - io.micronaut.jackson.JacksonDatabindFeature
[2/7] Performing analysis...  []                                                                         (8.1s @ 1.18GB)
   6,420 (90.79%) of  7,071 classes reachable
   9,304 (60.28%) of 15,434 fields reachable
  31,185 (83.06%) of 37,543 methods reachable
     480 classes,     0 fields, and     0 methods registered for reflection
       1 native library: -framework CoreServices

Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing java.lang.invoke.CallSite.setTargetNormal(java.lang.invoke.MethodHandle) 
Parsing context:
   at java.lang.invoke.CallSite.setTargetNormal(CallSite.java:286)
   at java.lang.invoke.MutableCallSite.setTarget(MutableCallSite.java:156)
   at java.lang.invoke.SwitchPoint.invalidateAll(SwitchPoint.java:225)
   at org.codehaus.groovy.vmplugin.v8.IndyInterface.invalidateSwitchPoints(IndyInterface.java:186)
   at org.codehaus.groovy.vmplugin.v8.IndyInterface.lambda$static$0(IndyInterface.java:172)

```

**Comment by linghengqian** [comment]
- Your error is the same as what I saw at https://github.com/apache/shardingsphere/pull/21109 .  In https://github.com/oracle/graal/issues/4492 and https://issues.apache.org/jira/projects/GROOVY/issues/GROOVY-10643 , some friends in the community found that GraalVM Native Image failed to build Groovy 4.0.2 issue, and made some fixes, but maybe not fully addressing this use case.  Since I'm on vacation, I haven't had time to investigate.

**Comment by sdelamo** [comment]
There are no plans to support GralaVM for Micronaut Framework and Apache Groovy
